apiVersion: batch/v1
kind: CronJob
metadata:
  name: every-five
  namespace: openfaas
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: openfaas-cli
            image: ghcr.io/openfaas/faas-cli:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            args:
            - -c
            - echo "verbose" | faas-cli invoke reporting -g http://gateway.openfaas:8080
          restartPolicy: OnFailure